FROM python:3.12.14-slim-bookworm

RUN truncate -s 32G /disk.img

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . . 
EXPOSE 8000

CMD ["python", "manage.py", "runserver",  "0.0.0.0:8000"]
