name: django-main 

services: 
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: django-image
    container_name: django-container
    ports:
      - "8000:8000"
    volumes: 
      - .:/app

    environment:
      - SOLR_URL=http://localhost:8983/solr/ai_search

networks:
  app-net:
    driver: bridge